steps:
# 1. Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'
    - './3-gke-deployment/app'

# 2. Push the Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'

# 3. Initialize Terraform
- name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'terraform'
  dir: 'terraform'
  args:
    - 'init'

# 4. Apply Terraform configuration
- name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'terraform'
  dir: 'terraform'
  args:
    - 'apply'
    - '-auto-approve'
    - '-var=project_id=${PROJECT_ID}'
    - '-var=region=${_REGION}'
    - '-var=image_tag=${SHORT_SHA}'

# Store the image name for other builds
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'

# Default substitutions
substitutions:
  _REGION: 'us-central1'
  _REPO_NAME: 'gke-apps'
  _IMAGE_NAME: 'hello-gke'
