timeout: 1200s # 20 minutes
options:
  logging: CLOUD_LOGGING_ONLY

steps:
# 1. Lint shell scripts
- name: 'koalaman/shellcheck-alpine'
  args: 
    - '1-gcp-setup/*.sh'
    - '2-host-setup/*.sh'
    - '3-cloud-run-deployment/*.sh'
    - '3-gke-deployment/*.sh'

# 2. Terraform Code Quality Checks
- name: 'hashicorp/terraform:1.8.4'
  entrypoint: 'sh'
  dir: 'terraform'
  args:
    - '-c'
    - |
      terraform fmt -check
      terraform init -backend=false
      terraform validate

# 3a. Build Docker (Cloud Run)
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'
    - './3-cloud-run-deployment/app'

# 3b. Build Docker (GKE)
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/hello-gke:${SHORT_SHA}'
    - './3-gke-deployment/app'

# 4a. Push (Cloud Run)
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}']

# 4b. Push (GKE)
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/hello-gke:${SHORT_SHA}']

# 5. Initialize Terraform
- name: 'hashicorp/terraform:1.8.4'
  entrypoint: 'sh'
  dir: 'terraform'
  secretEnv: ['TF_VAR_tf_state_bucket']
  args:
    - '-c'
    # FIXED: Use $$ to escape the variable for Cloud Build substitution
    - 'echo "Initializing with bucket: $$TF_VAR_tf_state_bucket" && terraform init -backend-config="bucket=$$TF_VAR_tf_state_bucket"'

# 6. Apply Terraform
- name: 'hashicorp/terraform:1.8.4'
  entrypoint: 'sh'
  dir: 'terraform'
  secretEnv: 
    - 'TF_VAR_duckdns_token'
    - 'TF_VAR_email_address'
    - 'TF_VAR_domain_name'
    - 'TF_VAR_gcs_bucket_name'
    - 'TF_VAR_tf_state_bucket'
    - 'TF_VAR_backup_dir'
    - 'TF_VAR_billing_account_id'
  args:
    - '-c'
    - |
      terraform apply -auto-approve \
        -var="project_id=${PROJECT_ID}" \
        -var="region=${_REGION}" \
        -var="image_tag=${SHORT_SHA}"

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/hello-gke:${SHORT_SHA}'

substitutions:
  _REGION: 'us-central1'
  _REPO_NAME: 'gke-apps'
  _IMAGE_NAME: 'hello-cloud-run'

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/duckdns_token/versions/latest
    env: 'TF_VAR_duckdns_token'
  - versionName: projects/$PROJECT_ID/secrets/email_address/versions/latest
    env: 'TF_VAR_email_address'
  - versionName: projects/$PROJECT_ID/secrets/domain_name/versions/latest
    env: 'TF_VAR_domain_name'
  - versionName: projects/$PROJECT_ID/secrets/gcs_bucket_name/versions/latest
    env: 'TF_VAR_gcs_bucket_name'
  - versionName: projects/$PROJECT_ID/secrets/tf_state_bucket/versions/latest
    env: 'TF_VAR_tf_state_bucket'
  - versionName: projects/$PROJECT_ID/secrets/backup_dir/versions/latest
    env: 'TF_VAR_backup_dir'
  - versionName: projects/$PROJECT_ID/secrets/billing_account_id/versions/latest
    env: 'TF_VAR_billing_account_id'